[package]
name = "desktop-background"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = [ "rwh_05" ] }
pixels = "0.13"
chrono = "0.4"
clap = { version = "4.5", features = [ "derive" ] }
image = "0.25"
